key_frames_dir: data/Lynx/style/
frames_dir: data/Lynx/sequence/
logdir: data/Lynx/logs/

iters: 10000
max_time_minutes: null
device: 'cuda:0'

batch_size: 1
disable_augment: false

resize: 512

key_weight: 1
style_weight: 100
structure_weight: 5e-6

vgg_layers: [1, 3, 6, 8, 11, 13, 15, 17, 20, 22, 24, 26, 29, 31, 33, 35]